<?php
declare(strict_types=1);

// OpenDataHub SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

OpenDataHubUtility::setRegistrar(function (OpenDataHubUtility $u): void {
    $u->clean = [OpenDataHubClean::class, 'call'];
    $u->done = [OpenDataHubDone::class, 'call'];
    $u->make_error = [OpenDataHubMakeError::class, 'call'];
    $u->feature_add = [OpenDataHubFeatureAdd::class, 'call'];
    $u->feature_hook = [OpenDataHubFeatureHook::class, 'call'];
    $u->feature_init = [OpenDataHubFeatureInit::class, 'call'];
    $u->fetcher = [OpenDataHubFetcher::class, 'call'];
    $u->make_fetch_def = [OpenDataHubMakeFetchDef::class, 'call'];
    $u->make_context = [OpenDataHubMakeContext::class, 'call'];
    $u->make_options = [OpenDataHubMakeOptions::class, 'call'];
    $u->make_request = [OpenDataHubMakeRequest::class, 'call'];
    $u->make_response = [OpenDataHubMakeResponse::class, 'call'];
    $u->make_result = [OpenDataHubMakeResult::class, 'call'];
    $u->make_point = [OpenDataHubMakePoint::class, 'call'];
    $u->make_spec = [OpenDataHubMakeSpec::class, 'call'];
    $u->make_url = [OpenDataHubMakeUrl::class, 'call'];
    $u->param = [OpenDataHubParam::class, 'call'];
    $u->prepare_auth = [OpenDataHubPrepareAuth::class, 'call'];
    $u->prepare_body = [OpenDataHubPrepareBody::class, 'call'];
    $u->prepare_headers = [OpenDataHubPrepareHeaders::class, 'call'];
    $u->prepare_method = [OpenDataHubPrepareMethod::class, 'call'];
    $u->prepare_params = [OpenDataHubPrepareParams::class, 'call'];
    $u->prepare_path = [OpenDataHubPreparePath::class, 'call'];
    $u->prepare_query = [OpenDataHubPrepareQuery::class, 'call'];
    $u->graphql_body = [OpenDataHubGraphql::class, 'body'];
    $u->graphql_errors = [OpenDataHubGraphql::class, 'errors'];
    $u->result_basic = [OpenDataHubResultBasic::class, 'call'];
    $u->result_body = [OpenDataHubResultBody::class, 'call'];
    $u->result_headers = [OpenDataHubResultHeaders::class, 'call'];
    $u->transform_request = [OpenDataHubTransformRequest::class, 'call'];
    $u->transform_response = [OpenDataHubTransformResponse::class, 'call'];
});
